#!/bin/sh

echo "*****Running unit tests******"

stash_commit="$(git stash create)"
git reset —-hard

npm run devcheck

status=$?

if [[ -n "${stash_commit}" ]]
then git stash apply "${stash_commit}"
fi

exit $status
